Ts_app/urls.py
# coding:utf8
'''
Created on 2016年8月3日

@author: zhangq
'''

from django.conf.urls import url
from Ts_app import views
urlpatterns = [
    url(r'^$', views.homeview),
    url(r'^ts_app/$', views.indexview),
    url(r'^ajax_radio/', views.radioview),
    url(r'^equipment/$', views.rentview),
    url(r'^testlink/$', views.testlinkview),
    url(r'^testcase/(\d+)$', views.test_case_view),
    url(r'^testsuite/(\d+)$', views.test_suite_view),
    url(r'^testreport/(.+)', views.test_report_view),
    url(r'^testbuild/(\d+)$', views.test_build_view),
    url(r'^testbuild/result/(\d+)$', views.test_result_view),
    url(r'^testbuild/(\d+)/suite/(\d+)$', views.test_result_suite_view),
    url(r'^editcase/', views.edit_case_view),
    url(r'^editsuite/', views.edit_suite_view),
    url(r'^ajax_list/', views.ajaxview),
    url(r'^ajax_dic/', views.ajaxdicview),
    url(r'^create_excel/(\d+)/(\d+)$', views.excelview),
    url(r'^testcase/(?P<article_id>\d+)/comment/$', views.CommentPostView.as_view(), name='comment'),
    ]

hdcp_study/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings
import django

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    #url(r'', include(
    #    'hdcp_app.urls', namespace='hdcp_app', app_name='hdcp_app')),
    url(r'', include('Ts_app.urls', namespace='Ts_app', app_name='Ts_app')),
    #url(r'^media/(?P<path>.*)$', django.views.static.serve,{'document_root':settings.MEDIA_ROOT}),
    #url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root':'/home/anna/Documents/django_py/showImg/image/pic'}),
]

Ts_app/models.py
#coding:utf8
from __future__ import unicode_literals

from django.db import models
import django.utils.timezone as timezone


# Create your models here.
class user_info(models.Model):
    server_name = models.CharField(max_length=1000)
    user_name = models.CharField(max_length=100)
    rent_time = models.DateTimeField(
        'use end time', default=timezone.now)


class RentDB(models.Model):
    d_type = models.CharField(max_length=100)
    d_id = models.CharField(max_length=100)
    d_pic = models.ImageField(upload_to='img')
    p_name = models.CharField(max_length=100)

class TestlinkBuild(models.Model):
    build_name = models.CharField(max_length=100, null=True)
    def __str__(self):
        #return "TestlinkDB33"
        return self.build_name
    def type_name(self):
        return "TestlinkBuild"
class TestlinkReport(models.Model):
    
    test_case = models.ForeignKey('TestlinkCase',related_name='case_report',null=True)
    build_name = models.ForeignKey('TestlinkBuild', related_name='case_report',null=True)
    result_choice = (('Pass', 'pass'), ('Fail', 'fail'), ('Untest', 'untest'),('Block','block'))
    test_result = models.CharField(max_length=100, choices=result_choice, default='Untest')
    result_description = models.TextField(max_length=4000, null=True, blank=True)
    result_pic = models.ImageField(upload_to='img', null=True,blank=True)
    result_video = models.FileField(upload_to='video',null=True,blank=True)
    result_log = models.FileField(upload_to='log',null=True,blank=True)

class TestlinkDB(models.Model):
    # parent_suite_name = models.CharField(max_length=100)
    parent_suite_name = models.ForeignKey(
        'self',  related_name='children',blank=True,null=True,)
    suite_name = models.CharField(max_length=100,null=True, blank=True)
    suite_detail = models.TextField(default='null',blank=True)
    suite_id = models.CharField(max_length=100)

    def __str__(self):
        #return "TestlinkDB33"
        return self.suite_name
    def type_name(self):
        return "TestlinkDB"


class TestlinkCase(models.Model):
    case_name = models.CharField(
        max_length=100,null=True, blank=True)
    case_sum = models.TextField(null=True, default='null')
    case_step = models.TextField(max_length=4000, null=True, blank=True)
    case_except = models.TextField(null=True, blank=True)
    case_suite = models.ForeignKey('TestlinkDB',
                                   blank=True, null=True,
                                   related_name='children_case')
    internalid = models.CharField(max_length=1000,default='null')

    def __str__(self):
        return self.case_name
    
    def type_name(self):
        return "TestlinkCase"

class BlogComment(models.Model):
    user_name = models.CharField('评论者名字',max_length=100)
    body = models.TextField('评论内容')
    created_time = models.DateTimeField('评论发表时间',auto_now_add=True)
    ariticle = models.ForeignKey('TestlinkCase', verbose_name='评论所属文章',on_delete=models.CASCADE)
    def __str__(self):
        return self.body[:20]

Ts_app/views.py
# coding:utf-8
from django.shortcuts import render, get_object_or_404,HttpResponseRedirect
from django.http import JsonResponse
from Ts_app.form import AddForm, AddUser, StreamForm, RentForm, TestlinkForm, TestlinkForm_case, TestlinkForm_suite, BlogCommentForm
from Ts_app.models import user_info, RentDB, TestlinkDB, TestlinkCase, TestlinkReport, TestlinkBuild, BlogComment
from django.views.generic.edit import CreateView, FormView
from Ts_app.switch_stream_Worker import switch_stream_Worker
from datetime import datetime
from Ts_app.XML_CSV import XML_CSV
import markdown2
import xlwt,xlrd



import sys
reload(sys)
sys.setdefaultencoding("utf-8")

def homeview(request):
    test = [('States',1), [('Kansas',2), [('Lawrence',3), ('Topeka',4), ('Illinois',5)]]]
    return render(request, 'Ts_app/home.html', {'test':test})

# Ts_app页面的逻辑函数
def indexview(request):
    if request.method == 'POST':  # 注释
        form = AddForm()
        form_user = AddUser()
        form_stream = StreamForm()
        user_obj = user_info.objects.all()
        if 'switch_file' in request.POST:
            form_stream = StreamForm(request.POST)
            if form_stream.is_valid():
                host_name = form_stream.cleaned_data['host_name']
                stream_path = form_stream.cleaned_data['stream_path']
                connect_obj = switch_stream_Worker()
                result_num = connect_obj.run_switch_one(
                    r"%s" % host_name, stream_path)
                return render(request, 'Ts_app/index.html', {
                    'form_stream': form_stream, 'form': form,
                    'result_num': result_num, 'form_user': form_user,
                    'user_obj': user_obj})
        if 'switch' in request.POST:
            form = AddForm(request.POST)
            if form.is_valid():
                host_name = form.cleaned_data['host_name']
                stream_path = form.cleaned_data['stream_path']
                modulation = form.cleaned_data['modulation']
                frame_mode = form.cleaned_data['frame_mode']
                code_rate = form.cleaned_data['code_rate']
                band_width = form.cleaned_data['bandwidth']
                connect_obj = switch_stream_Worker()
                result_num = connect_obj.run_switch(
                    r"%s" % host_name, stream_path, modulation,
                    frame_mode, code_rate, band_width)
                return render(request, 'Ts_app/index.html', {
                    'form_stream': form_stream, 'form': form,
                    'result_num': result_num, 'form_user': form_user,
                    'user_obj': user_obj})
        if 'rent' in request.POST:
            form_user = AddUser(request.POST)
            if form_user.is_valid():
                servername = form_user.cleaned_data['server_name']
                print servername
                try:
                    form_user = AddUser(
                        request.POST, instance=user_info.objects.get(
                            server_name=servername))
                except:
                    pass
                form_user.save()
                return render(request, 'Ts_app/index.html', {
                    'form_stream': form_stream, 'form': form,
                    'form_user': form_user, 'user_obj': user_obj})
        # 注释掉了，暂时不用
        if 'check_box_list_bak' in request.POST:
            print "fff"
            radio = request.POST.get('check_box_list')
            radio = int(radio)-1
            host_name = request.POST.get('host_name')
            print host_name
            modulation = ['3', '2', '3', '3', '3', '5', '4']
            frame_mode = ['1', '2', '1', '2', '3', '3', '2']
            code_rate = ['1', '3', '2', '3', '3', '2', '3']
            carrier_mode = ['1', '2', '1', '2', '1', '1', '2']
            print host_name, modulation[radio],\
                frame_mode[radio], code_rate[radio]
            connect_obj = switch_stream_Worker()
            result_num = connect_obj.run_switch_mode(
                r"%s" % host_name, modulation[radio],
                frame_mode[radio], code_rate[radio], carrier_mode[radio])
            return render(request, 'Ts_app/index.html', {
                'form_stream': form_stream, 'form': form,
                'result_num': result_num, 'form_user': form_user,
                'user_obj': user_obj})
    else:
        form = AddForm()
        form_stream = StreamForm()
        form_user = AddUser()
        user_obj = user_info.objects.all()
    return render(request, 'Ts_app/index.html', {
        'form_stream': form_stream, 'form': form,
        'form_user': form_user, 'user_obj': user_obj})


# equipment页面的逻辑函数
def rentview(request):
    rent_obj = RentDB.objects.all()
    if request.method == 'POST':
        print "b"
        form2 = RentForm()
        if 'rent' in request.POST:
            print "c"
            form2 = RentForm(request.POST or None, request.FILES)
            if form2.is_valid():
                device_id = form2.cleaned_data['d_id']
                try:
                    form2 = RentForm(
                        request.POST, request.FILES,
                        instance=RentDB.objects.get(d_id=device_id))
                except:
                    pass
                form2.save()
                return render(request, 'Ts_app/rent.html', {
                    'form2': form2, 'rent_obj': rent_obj})

    else:
        form2 = RentForm()

    return render(request, 'Ts_app/rent.html', {
        'form2': form2, 'rent_obj': rent_obj})

def excelview(request,suite_id,build_id):
    test_suite_root = TestlinkDB.objects.get(id=int(suite_id))
    #test_suite_root = TestlinkDB.objects.filter(suite_name="AIrBee")
    test_case_list = get_case_list(test_suite_root,test_suite_root.suite_name,build_id)
    #print test_case_list
    print test_suite_root
    print "aaaaa"
    return render(request, 'Ts_app/testlink.html')

    
    


# 用ajax请求动态内容的逻辑函数
def ajaxview(request):
    a = range(30)
    return JsonResponse(a, safe=False)


def ajaxdicview(request):
    name_dict = {'twz': 'Love python and Django', 'zqxt': datetime.now()}
    return JsonResponse(name_dict)


def radioview(request):
        # print request.GET['radio_id']
        if request.method == 'GET':
            radio = int(request.GET['radio_id'])-1
            host_name = request.GET['host_id']
            modulation = ['3', '2', '3', '3', '3', '5', '4']
            frame_mode = ['1', '2', '1', '2', '3', '3', '2']
            code_rate = ['1', '3', '2', '3', '3', '2', '3']
            carrier_mode = ['1', '2', '1', '2', '1', '1', '2']
            connect_obj = switch_stream_Worker()
            result_num = connect_obj.run_switch_mode(
                r"%s" % host_name, modulation[radio],
                frame_mode[radio], code_rate[radio], carrier_mode[radio])
            print 1
            return JsonResponse(result_num, safe=False)
        else:
            print "no find check box in request"
            print request.method

def get_case_list(root_node,suite_name,build_id):
    exl_obj = xlwt.Workbook()
    num = 1
    i = root_node
    sheet_1 = exl_obj.add_sheet(suite_name, cell_overwrite_ok=False)
    raw_0 = ["suite_name","case_name","test_step","test_except","test_result","result_description"]
    for j in range(6):
        sheet_1.write(0,j,raw_0[j])
    print i.suite_name
    sheet_1.write(num,0,i.suite_name)
    num = num + 1
    # 目录的case子节点
    child_case = i.children_case.all()
    for l in child_case:
        #sheet_1.write(num,1,l.case_name)
        #sheet_1.write(num,2,l.case_step)
        #sheet_1.write(num,3,l.case_except)
        if int(build_id):
            m = l.case_report.filter(build_name=build_id).order_by('-id')
            if m:
                _test_result = m[0].test_result
                _result_description = m[0].result_description
                sheet_1.write(num,4,_test_result)
                sheet_1.write(num,5,_result_description)
                if _test_result:
                    sheet_1.write(num,1,l.case_name)
                    sheet_1.write(num,2,l.case_step)
                    sheet_1.write(num,3,l.case_except)
                    #sheet_1.write(num,4,l.case)
                    num = num + 1
        else:
            sheet_1.write(num,1,l.case_name)
            sheet_1.write(num,2,l.case_step)
            sheet_1.write(num,3,l.case_except)
            #sheet_1.write(num,4,l.case)
            num = num + 1
        
    # 目录的目录子节点
    children = i.children.all()
    for k in children:
        sheet_1.write(num,0,k.suite_name)
        num = num + 1
        for l in k.children_case.all():
            #sheet_1.write(num,1,l.case_name)
            #sheet_1.write(num,2,l.case_step)
            #sheet_1.write(num,3,l.case_except)
            if int(build_id):
                m = l.case_report.filter(build_name=build_id).order_by('-id')
                if m:
                    _test_result = m[0].test_result
                    _result_description = m[0].result_description
                    sheet_1.write(num,4,_test_result)
                    sheet_1.write(num,5,_result_description)
                    if _test_result:
                        sheet_1.write(num,1,l.case_name)
                        sheet_1.write(num,2,l.case_step)
                        sheet_1.write(num,3,l.case_except)
                        num = num + 1
            else:
                sheet_1.write(num,1,l.case_name)
                sheet_1.write(num,2,l.case_step)
                sheet_1.write(num,3,l.case_except)
                #sheet_1.write(num,4,l.case)
                num = num + 1
    exl_obj.save("/var/www/public_html/test_case.xls")
    #return play_list

#excel生成
def get_case_list_bak(root_node,suite_name):
    exl_obj = xlwt.Workbook()
    num = 1
    #for i in root_node:
    #    if i.type_name() == "TestlinkDB":
    i = root_node

Ts_app/templates/Ts_app/blogcomment.html
{% for i in test_case_list %}

<div class="comment">
    <div class="comment-main">
        <p class="head">评论详情</p>
        <form method="post" action="{% url 'Ts_app:comment' i.id %}">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
            </div>
            <button type="submit" class="com-button">评论</button>
        </form>
        <p class="comment-count">共{{ 0 }}条评论</p>
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
{#                <img src="月英1.jpg" class="user-avatar">#}
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.created_time }}</time>
                <div class="comment-content">
                    {{ comment.body|linebreaksbr }}
                </div>
{#                <a href="">回复</a>#}
            </div>
            <hr>
        {% endfor %}
    </div>
</div>
{% endfor %}

Ts_app/templates/Ts_app/editcase.html
<form method='POST' enctype="multipart/form-data">
{% csrf_token %}
{{ form_obj_2 }}
<input type='submit' name="add_case" value="add_case"></input>
</form>
<br>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
{% load tree_list %}
{{ test_suite_list|li_tree }}

Ts_app/templates/Ts_app/editsuite.html
<form method='POST' enctype="multipart/form-data">
{% csrf_token %}
{{ form_obj_3 }}
<input type='submit' name="add_suite" value="add_suite"></input>
</form>
<br>
<br>
<br>
<br>
{% load tree_list %}
{{ test_suite_list|li_tree }}

Ts_app/templates/Ts_app/home.html
{% load tree_list %}



<div class="unit-inner">

<a href="/ts_app">TS_APP</a>

<a href="/equipment">equipment</a>

<a href="/testlink">testlink</a>

</div>

Ts_app/templates/Ts_app/index.html
<html>
<body>
<form method='post'> 
{% csrf_token %}
{{ form }}
<input type="submit" name="switch" value="switch" action="switch">
</input>
</form>
<form method='post'>
{% csrf_token %}
{{ form_stream }}
<input type="submit" name="switch_file" value='switch'>
</input>
</form>
{% for i in result_num %}
<a>{{i}}</a>
</br>
{% endfor %}
</br>


<table border=1>
 <col width=82 span=7 style='width:54pt'>
 
<form method='post'>
{% csrf_token %}
<select id="host_id" name="host_id">
<option value="bjdqa150804">bjdqa150804</option>
<option value="bjdittest">bjdittest</option>
<option value="bjdlise2">bjdlise2</option>
</select>
<div>
<p>result: <span id='result'></span></p>
</div>

<tr>
<td>mode</td>
<td>carrier mode</td>
<td>Modulation</td>
<td>code rate</td>
<td>frame mode</td>
<td>inter leaving</td>
<td>rate</td>
<td>
<input type="button" value='submit' id="radio_button">
</td>
</tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl67 width=72 style='height:16.5pt;width:54pt'>&#27169;&#24335;<font
  class="font7">1<span style='mso-spacerun:yes'>&nbsp;</span></font></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>C=3780<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>16QAM<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>0.4</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>PN945<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>720</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>9.626</span></td>
<td>
<input type="radio" value="1" name="check_box_list"/>
</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl67 width=72 style='height:16.5pt;width:54pt'>&#27169;&#24335;<font
  class="font7">2<span style='mso-spacerun:yes'>&nbsp;</span></font></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>C=1<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>4QAM<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>0.8</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>PN595<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>720</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>10.396</span></td>
<td>
<input type="radio" value="2" name="check_box_list"/>
</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl67 width=72 style='height:16.5pt;width:54pt'>&#27169;&#24335;<font
  class="font7">3<span style='mso-spacerun:yes'>&nbsp;</span></font></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>C=3780<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>16QAM<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>0.6</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>PN945<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>720</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>14.438</span></td>
<td>
<input type="radio" value="3" name="check_box_list"/>
</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl67 width=72 style='height:16.5pt;width:54pt'>&#27169;&#24335;<font
  class="font7">4<span style='mso-spacerun:yes'>&nbsp;</span></font></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>C=1<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>16QAM<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>0.8</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>PN595<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>720</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>20.791</span></td>
<td>
<input type="radio" value="4" name="check_box_list"/>
</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl67 width=72 style='height:16.5pt;width:54pt'>&#27169;&#24335;<font
  class="font7">5<span style='mso-spacerun:yes'>&nbsp;</span></font></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>C=3780<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>16QAM<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>0.8</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>PN420<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>720</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>21.658</span></td>
<td>
<input type="radio" value="5" name="check_box_list"/>
</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl67 width=72 style='height:16.5pt;width:54pt'>&#27169;&#24335;<font
  class="font7">6<span style='mso-spacerun:yes'>&nbsp;</span></font></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>C=3780<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>64QAM<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>0.6</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>PN420<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>720</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>24.365</span></td>
<td>
<input type="radio" value="6" name="check_box_list"/>
</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl67 width=72 style='height:16.5pt;width:54pt'>&#27169;&#24335;<font
  class="font7">7<span style='mso-spacerun:yes'>&nbsp;</span></font></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>C=1<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>32QAM<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>0.8</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>PN595<span
  style='mso-spacerun:yes'>&nbsp;</span></span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>720</span></td>
  <td class=xl68 width=72 style='width:54pt'><span lang=EN-US>25.989</span></td>
<td>
<input type="radio" value="7" name="check_box_list"/>
</td>
 </tr>
 <tr height=0 style='display:none'>
  <td width=72 style='width:54pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=72 style='width:54pt'></td>
 </tr>
</form>
</table>



</br>
</br>
</br>



<form method='post'>
{% csrf_token %}
{{ form_user }}
<input type="submit" name="rent" value="rent" action="rent">

</form>
</br>
<table border=1>
<tr>
<td>
<a>the stream card</a>
</td>
<td>
<a>current user</a>
</td>
<td>
<a>rent time</a>
</td>
</tr>
{% for info_use in user_obj %}
<tr>
<td>
<a>{{info_use.server_name}} </a>
</td>
<td>
<a>{{info_use.user_name}}  </a>
</td>
<td>
<a>{{info_use.rent_time}}  </a>
</td>
</tr>
{% endfor %}
</table>

<script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
	$(document).ready(function(){
		$("#radio_button").click(function(){
			$('#result').html("loading...");
			var r_id = $("input[name='check_box_list']:checked").val();
			var h_name = $("#host_id").val();
			$.getJSON("/ajax_radio/",{radio_id:r_id,host_id:h_name},function(ret){
				$('#result').html("");
				for(var i = ret.length-1;i>=0;i--){
					$('#result').append('</br>'+ret[i])
				};
				
				
			})
	
		});	
	});
</script>
</body>
</html>

Ts_app/templates/Ts_app/testcase.html
<head>
<meta charset="UTF-8">
<title>测试用例</title>
</head>
<a href="/testlink/">回首页</a><br>
{% autoescape off %}
{% for i in test_case_list %}
<b>name:</b><br>
<font color="green">
{{ i.case_name }}
</font>
<br>
<b>step:</b><br>
<font color="blue">
{{ i.case_step|linebreaksbr }}<br>
{{ i.content }}<br>

</font>
<b>except result:</b><br>
<font color="grey">
{{ i.case_except|linebreaksbr }}<br>
</font>

<br>


<button onclick="window.location.href=('/admin/Ts_app/testlinkcase/{{ i.id }}/change')">


edit case
</button>



{% endfor %}




{% endautoescape %}

{% include 'Ts_app/blogcomment.html' %}